blank_issues_enabled: true
contact_links:
  - name: [对话] BookwormPRO Project Discord
    url: https://discord.gg/BookwormPRO
    about: For quick questions, showcasing projects, sharing skills, and community chat.
  - name: 📖 Documentation
    url: https://github.com/huakoh/BookwormPRO/blob/main/README.md
    about: Check the README and docs before opening an issue.
  - name: 🤝 Contributing Guide
    url: https://github.com/huakoh/BookwormPRO/blob/main/CONTRIBUTING.md
    about: Read this before submitting a PR.
