#!/usr/bin/env python3
"""
BookwormPRO i18n — 字符串提取工具。

Scans Python source files for ``_("text")`` calls and generates/updates
``locale/bookwormpro.pot`` (template).  Uses ``babel.messages.extract``
if available, otherwise falls back to regex scan.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
POT_PATH = PROJECT_ROOT / "locale" / "bookwormpro.pot"

# Regex for _("literal string") — captures single and double quoted strings
_RE_I18N = re.compile(
    r'_\("([^"\\]*(?:\\.[^"\\]*)*)"\)|'  # _("...")
    r"_\(\"([^\"\\\\]*(?:\\\\.[^\"\\\\]*)*)\"\)|"  # _("...")
    r"_\\('([^'\\\\]*(?:\\\\.[^'\\\\]*)*)'\\)"  # _('...')
    r"_\\('([^'\\\\]*(?:\\\\.[^'\\\\]*)*)'\\)",  # _('...')
)


def extract_from_file(filepath: Path) -> set[str]:
    """Extract i18n strings from a Python file."""
    strings = set()
    try:
        content = filepath.read_text(encoding="utf-8")
    except Exception:
        return strings

    for match in re.finditer(r'_\(["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)', content):
        s = match.group(1)
        if s.strip():
            strings.add(s)
    return strings


def extract_all(source_dirs: list[str] | None = None) -> dict[str, set[str]]:
    """Scan all Python files and return {filepath: {strings}}."""
    if source_dirs is None:
        source_dirs = [
            str(PROJECT_ROOT / "bwm_cli"),
            str(PROJECT_ROOT / "agent"),
            str(PROJECT_ROOT / "gateway"),
            str(PROJECT_ROOT / "acp_adapter"),
        ]

    results: dict[str, set[str]] = {}
    for src in source_dirs:
        src_path = Path(src)
        if not src_path.exists():
            continue
        for py_file in src_path.rglob("*.py"):
            strings = extract_from_file(py_file)
            if strings:
                results[str(py_file.relative_to(PROJECT_ROOT))] = strings
    return results


def update_pot(strings: dict[str, set[str]]):
    """Update the .pot template file with extracted strings."""
    # Collect unique strings
    all_strings: set[str] = set()
    for file_strings in strings.values():
        all_strings.update(file_strings)

    if not all_strings:
        print("[i18n] No translatable strings found.")
        return

    all_sorted = sorted(all_strings)

    # Generate .pot content
    lines = [
        '# BookwormPRO i18n — Translation Template',
        '# Generated by scripts/extract_strings.py',
        '#',
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: BookwormPRO 7.0.0\\n"',
        f'"POT-Creation-Date: {_now()}\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '',
    ]

    for s in all_sorted:
        lines.append(f'msgid "{_escape(s)}"')
        lines.append('msgstr ""')
        lines.append('')

    POT_PATH.parent.mkdir(parents=True, exist_ok=True)
    POT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"[i18n] Wrote {len(all_sorted)} strings to {POT_PATH}")


def _escape(s: str) -> str:
    """Escape special characters for .po format."""
    return s.replace('\\', '\\\\').replace('"', '\\"')


def _now() -> str:
    """ISO datetime for POT header."""
    from datetime import datetime, timezone, timedelta
    tz = timezone(timedelta(hours=8))
    return datetime.now(tz).strftime("%Y-%m-%d %H:%M%z")


def main():
    print("[i18n] Extracting translatable strings...")
    results = extract_all()
    print(f"[i18n] Found strings in {len(results)} files")
    update_pot(results)


if __name__ == "__main__":
    main()
